-- 코드를 입력하세요
WITH NEWTABLE AS
(
    SELECT BOOK_ID, SUM(SALES) TOTALSALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
)

SELECT B.CATEGORY, SUM(N.TOTALSALES) TOTAL_SALES
FROM BOOK B INNER JOIN NEWTABLE N
ON B.BOOK_ID = N.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;